-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity execute is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    opcode : IN STD_LOGIC_VECTOR (3 downto 0);
    ra_addr : IN STD_LOGIC_VECTOR (4 downto 0);
    rb_addr : IN STD_LOGIC_VECTOR (4 downto 0);
    rc_addr : IN STD_LOGIC_VECTOR (4 downto 0);
    imd_data : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of execute is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "execute_execute,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg225-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.542000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=63,HLS_SYN_LUT=306,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal lsm_instance_reg_file_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lsm_instance_reg_file_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lsm_instance_mem_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ra_addr_read_reg_307 : STD_LOGIC_VECTOR (4 downto 0);
    signal lsm_instance_reg_file_addr_reg_312 : STD_LOGIC_VECTOR (4 downto 0);
    signal lsm_instance_reg_file_addr_1_reg_318 : STD_LOGIC_VECTOR (4 downto 0);
    signal rc_addr_read_reg_324 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal opcode_read_read_fu_80_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal opcode_read_reg_331 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln51_fu_230_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_3_fu_234_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_2_fu_240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_1_fu_246_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_fu_252_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_1_reg_366 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal result_6_reg_159 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln19_fu_194_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln19_1_fu_199_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_fu_262_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln94_fu_271_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln13_fu_281_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln12_2_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln89_1_fu_298_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln19_2_fu_303_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lsm_instance_reg_file_ce1_local : STD_LOGIC;
    signal lsm_instance_reg_file_address1_local : STD_LOGIC_VECTOR (4 downto 0);
    signal lsm_instance_reg_file_ce0_local : STD_LOGIC;
    signal lsm_instance_reg_file_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal lsm_instance_reg_file_we0_local : STD_LOGIC;
    signal lsm_instance_reg_file_we1_local : STD_LOGIC;
    signal lsm_instance_reg_file_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal lsm_instance_mem_ce0_local : STD_LOGIC;
    signal lsm_instance_mem_address0_local : STD_LOGIC_VECTOR (9 downto 0);
    signal lsm_instance_mem_we0_local : STD_LOGIC;
    signal result_4_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal address_1_fu_258_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal address_fu_267_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mem_addr_fu_294_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_condition_174 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component execute_lsm_instance_reg_file_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component execute_lsm_instance_mem_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    lsm_instance_reg_file_U : component execute_lsm_instance_reg_file_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => lsm_instance_reg_file_address0_local,
        ce0 => lsm_instance_reg_file_ce0_local,
        we0 => lsm_instance_reg_file_we0_local,
        d0 => imd_data,
        q0 => lsm_instance_reg_file_q0,
        address1 => lsm_instance_reg_file_address1_local,
        ce1 => lsm_instance_reg_file_ce1_local,
        we1 => lsm_instance_reg_file_we1_local,
        d1 => lsm_instance_reg_file_d1_local,
        q1 => lsm_instance_reg_file_q1);

    lsm_instance_mem_U : component execute_lsm_instance_mem_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => lsm_instance_mem_address0_local,
        ce0 => lsm_instance_mem_ce0_local,
        we0 => lsm_instance_mem_we0_local,
        d0 => lsm_instance_reg_file_q1,
        q0 => lsm_instance_mem_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    result_6_reg_159_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((opcode_read_read_fu_80_p2 = ap_const_lv4_1)) then 
                    result_6_reg_159 <= result_fu_252_p2;
                elsif ((opcode_read_read_fu_80_p2 = ap_const_lv4_2)) then 
                    result_6_reg_159 <= result_1_fu_246_p2;
                elsif ((opcode_read_read_fu_80_p2 = ap_const_lv4_3)) then 
                    result_6_reg_159 <= result_2_fu_240_p2;
                elsif ((opcode_read_read_fu_80_p2 = ap_const_lv4_4)) then 
                    result_6_reg_159 <= result_3_fu_234_p2;
                elsif ((opcode_read_read_fu_80_p2 = ap_const_lv4_8)) then 
                    result_6_reg_159 <= zext_ln51_fu_230_p1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln12_1_reg_366 <= grp_fu_189_p2;
                opcode_read_reg_331 <= opcode;
                rc_addr_read_reg_324 <= rc_addr;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                lsm_instance_reg_file_addr_1_reg_318 <= zext_ln19_1_fu_199_p1(5 - 1 downto 0);
                lsm_instance_reg_file_addr_reg_312 <= zext_ln19_fu_194_p1(5 - 1 downto 0);
                ra_addr_read_reg_307 <= ra_addr;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, opcode_read_read_fu_80_p2, opcode_read_reg_331, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not((opcode_read_read_fu_80_p2 = ap_const_lv4_9)) and not((opcode_read_read_fu_80_p2 = ap_const_lv4_6)) and not((opcode_read_read_fu_80_p2 = ap_const_lv4_5)) and not((opcode_read_read_fu_80_p2 = ap_const_lv4_1)) and not((opcode_read_read_fu_80_p2 = ap_const_lv4_2)) and not((opcode_read_read_fu_80_p2 = ap_const_lv4_3)) and not((opcode_read_read_fu_80_p2 = ap_const_lv4_4)) and not((opcode_read_read_fu_80_p2 = ap_const_lv4_8)) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((opcode_read_reg_331 = ap_const_lv4_1) or ((opcode_read_reg_331 = ap_const_lv4_2) or ((opcode_read_reg_331 = ap_const_lv4_3) or ((opcode_read_reg_331 = ap_const_lv4_4) or (opcode_read_reg_331 = ap_const_lv4_8))))))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    address_1_fu_258_p1 <= lsm_instance_reg_file_q0(10 - 1 downto 0);
    address_fu_267_p1 <= lsm_instance_reg_file_q0(10 - 1 downto 0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_condition_174_assign_proc : process(opcode_read_reg_331, icmp_ln12_2_fu_276_p2)
    begin
                ap_condition_174 <= ((((((opcode_read_reg_331 = ap_const_lv4_4) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0)) or ((opcode_read_reg_331 = ap_const_lv4_8) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_3) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_2) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_1) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0)));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6_assign_proc : process(lsm_instance_reg_file_q0, lsm_instance_mem_q0, opcode_read_reg_331, ap_CS_fsm_state5)
    begin
        if (((not((opcode_read_reg_331 = ap_const_lv4_5)) and not((opcode_read_reg_331 = ap_const_lv4_9)) and not((opcode_read_reg_331 = ap_const_lv4_6)) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and ((opcode_read_reg_331 = ap_const_lv4_5) or (opcode_read_reg_331 = ap_const_lv4_9))))) then 
            ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6 <= lsm_instance_reg_file_q0;
        elsif (((opcode_read_reg_331 = ap_const_lv4_6) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6 <= lsm_instance_mem_q0;
        else 
            ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6;
    grp_fu_189_p2 <= "1" when (ra_addr_read_reg_307 = ap_const_lv5_0) else "0";
    icmp_ln12_2_fu_276_p2 <= "1" when (rc_addr_read_reg_324 = ap_const_lv5_0) else "0";

    lsm_instance_mem_address0_local_assign_proc : process(ap_CS_fsm_state2, opcode_read_read_fu_80_p2, ap_CS_fsm_state4, zext_ln89_fu_262_p1, zext_ln94_fu_271_p1, zext_ln89_1_fu_298_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            lsm_instance_mem_address0_local <= zext_ln89_1_fu_298_p1(10 - 1 downto 0);
        elsif (((opcode_read_read_fu_80_p2 = ap_const_lv4_6) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lsm_instance_mem_address0_local <= zext_ln94_fu_271_p1(10 - 1 downto 0);
        elsif (((opcode_read_read_fu_80_p2 = ap_const_lv4_5) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lsm_instance_mem_address0_local <= zext_ln89_fu_262_p1(10 - 1 downto 0);
        else 
            lsm_instance_mem_address0_local <= "XXXXXXXXXX";
        end if; 
    end process;


    lsm_instance_mem_ce0_local_assign_proc : process(ap_CS_fsm_state2, opcode_read_read_fu_80_p2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((opcode_read_read_fu_80_p2 = ap_const_lv4_6) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((opcode_read_read_fu_80_p2 = ap_const_lv4_5) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            lsm_instance_mem_ce0_local <= ap_const_logic_1;
        else 
            lsm_instance_mem_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    lsm_instance_mem_we0_local_assign_proc : process(ap_CS_fsm_state2, opcode_read_read_fu_80_p2)
    begin
        if (((opcode_read_read_fu_80_p2 = ap_const_lv4_6) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lsm_instance_mem_we0_local <= ap_const_logic_1;
        else 
            lsm_instance_mem_we0_local <= ap_const_logic_0;
        end if; 
    end process;


    lsm_instance_reg_file_address0_local_assign_proc : process(ap_CS_fsm_state1, lsm_instance_reg_file_addr_reg_312, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, zext_ln19_1_fu_199_p1, zext_ln19_2_fu_303_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            lsm_instance_reg_file_address0_local <= zext_ln19_2_fu_303_p1(5 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lsm_instance_reg_file_address0_local <= lsm_instance_reg_file_addr_reg_312;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            lsm_instance_reg_file_address0_local <= zext_ln19_1_fu_199_p1(5 - 1 downto 0);
        else 
            lsm_instance_reg_file_address0_local <= "XXXXX";
        end if; 
    end process;


    lsm_instance_reg_file_address1_local_assign_proc : process(ap_CS_fsm_state1, lsm_instance_reg_file_addr_reg_312, lsm_instance_reg_file_addr_1_reg_318, opcode_read_reg_331, icmp_ln12_1_reg_366, zext_ln19_fu_194_p1, zext_ln13_fu_281_p1, ap_CS_fsm_state3, icmp_ln12_2_fu_276_p2)
    begin
        if (((opcode_read_reg_331 = ap_const_lv4_6) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            lsm_instance_reg_file_address1_local <= lsm_instance_reg_file_addr_1_reg_318;
        elsif (((icmp_ln12_1_reg_366 = ap_const_lv1_0) and (opcode_read_reg_331 = ap_const_lv4_5) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            lsm_instance_reg_file_address1_local <= lsm_instance_reg_file_addr_reg_312;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and ((((((opcode_read_reg_331 = ap_const_lv4_4) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0)) or ((opcode_read_reg_331 = ap_const_lv4_8) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_3) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_2) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_1) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))))) then 
            lsm_instance_reg_file_address1_local <= zext_ln13_fu_281_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            lsm_instance_reg_file_address1_local <= zext_ln19_fu_194_p1(5 - 1 downto 0);
        else 
            lsm_instance_reg_file_address1_local <= "XXXXX";
        end if; 
    end process;


    lsm_instance_reg_file_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            lsm_instance_reg_file_ce0_local <= ap_const_logic_1;
        else 
            lsm_instance_reg_file_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    lsm_instance_reg_file_ce1_local_assign_proc : process(ap_start, ap_CS_fsm_state1, opcode_read_reg_331, icmp_ln12_1_reg_366, ap_CS_fsm_state3, icmp_ln12_2_fu_276_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((icmp_ln12_1_reg_366 = ap_const_lv1_0) and (opcode_read_reg_331 = ap_const_lv4_5) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and ((((((opcode_read_reg_331 = ap_const_lv4_4) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0)) or ((opcode_read_reg_331 = ap_const_lv4_8) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_3) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_2) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_1) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0)))) or ((opcode_read_reg_331 = ap_const_lv4_6) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            lsm_instance_reg_file_ce1_local <= ap_const_logic_1;
        else 
            lsm_instance_reg_file_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    lsm_instance_reg_file_d1_local_assign_proc : process(lsm_instance_mem_q0, opcode_read_reg_331, icmp_ln12_1_reg_366, result_6_reg_159, ap_CS_fsm_state3, ap_condition_174)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if (((icmp_ln12_1_reg_366 = ap_const_lv1_0) and (opcode_read_reg_331 = ap_const_lv4_5))) then 
                lsm_instance_reg_file_d1_local <= lsm_instance_mem_q0;
            elsif ((ap_const_boolean_1 = ap_condition_174)) then 
                lsm_instance_reg_file_d1_local <= result_6_reg_159;
            else 
                lsm_instance_reg_file_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            lsm_instance_reg_file_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    lsm_instance_reg_file_we0_local_assign_proc : process(ap_CS_fsm_state2, opcode_read_read_fu_80_p2, grp_fu_189_p2)
    begin
        if (((grp_fu_189_p2 = ap_const_lv1_0) and (opcode_read_read_fu_80_p2 = ap_const_lv4_9) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            lsm_instance_reg_file_we0_local <= ap_const_logic_1;
        else 
            lsm_instance_reg_file_we0_local <= ap_const_logic_0;
        end if; 
    end process;


    lsm_instance_reg_file_we1_local_assign_proc : process(opcode_read_reg_331, icmp_ln12_1_reg_366, ap_CS_fsm_state3, icmp_ln12_2_fu_276_p2)
    begin
        if ((((icmp_ln12_1_reg_366 = ap_const_lv1_0) and (opcode_read_reg_331 = ap_const_lv4_5) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and ((((((opcode_read_reg_331 = ap_const_lv4_4) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0)) or ((opcode_read_reg_331 = ap_const_lv4_8) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_3) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_2) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0))) or ((opcode_read_reg_331 = ap_const_lv4_1) and (icmp_ln12_2_fu_276_p2 = ap_const_lv1_0)))))) then 
            lsm_instance_reg_file_we1_local <= ap_const_logic_1;
        else 
            lsm_instance_reg_file_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    mem_addr_fu_294_p1 <= lsm_instance_reg_file_q1(10 - 1 downto 0);
    opcode_read_read_fu_80_p2 <= opcode;
    result_1_fu_246_p2 <= std_logic_vector(unsigned(lsm_instance_reg_file_q1) - unsigned(lsm_instance_reg_file_q0));
    result_2_fu_240_p2 <= (lsm_instance_reg_file_q1 and lsm_instance_reg_file_q0);
    result_3_fu_234_p2 <= (lsm_instance_reg_file_q1 or lsm_instance_reg_file_q0);
    result_4_fu_224_p2 <= "1" when (lsm_instance_reg_file_q1 = lsm_instance_reg_file_q0) else "0";
    result_fu_252_p2 <= std_logic_vector(unsigned(lsm_instance_reg_file_q0) + unsigned(lsm_instance_reg_file_q1));
    zext_ln13_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rc_addr_read_reg_324),64));
    zext_ln19_1_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rb_addr),64));
    zext_ln19_2_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rc_addr_read_reg_324),64));
    zext_ln19_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ra_addr),64));
    zext_ln51_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_4_fu_224_p2),32));
    zext_ln89_1_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mem_addr_fu_294_p1),64));
    zext_ln89_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(address_1_fu_258_p1),64));
    zext_ln94_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(address_fu_267_p1),64));
end behav;
