// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="execute_execute,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg225-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.542000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=63,HLS_SYN_LUT=306,HLS_VERSION=2025_1}" *)

module execute (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        opcode,
        ra_addr,
        rb_addr,
        rc_addr,
        imd_data,
        ap_return
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] opcode;
input  [4:0] ra_addr;
input  [4:0] rb_addr;
input  [4:0] rc_addr;
input  [31:0] imd_data;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] lsm_instance_reg_file_q0;
wire   [31:0] lsm_instance_reg_file_q1;
wire   [31:0] lsm_instance_mem_q0;
reg   [4:0] ra_addr_read_reg_307;
reg   [4:0] lsm_instance_reg_file_addr_reg_312;
reg   [4:0] lsm_instance_reg_file_addr_1_reg_318;
reg   [4:0] rc_addr_read_reg_324;
wire    ap_CS_fsm_state2;
wire   [3:0] opcode_read_read_fu_80_p2;
reg   [3:0] opcode_read_reg_331;
wire   [31:0] zext_ln51_fu_230_p1;
wire   [31:0] result_3_fu_234_p2;
wire   [31:0] result_2_fu_240_p2;
wire   [31:0] result_1_fu_246_p2;
wire   [31:0] result_fu_252_p2;
wire   [0:0] grp_fu_189_p2;
reg   [0:0] icmp_ln12_1_reg_366;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
reg   [31:0] result_6_reg_159;
reg   [31:0] ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln19_fu_194_p1;
wire   [63:0] zext_ln19_1_fu_199_p1;
wire   [63:0] zext_ln89_fu_262_p1;
wire   [63:0] zext_ln94_fu_271_p1;
wire   [63:0] zext_ln13_fu_281_p1;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln12_2_fu_276_p2;
wire   [63:0] zext_ln89_1_fu_298_p1;
wire   [63:0] zext_ln19_2_fu_303_p1;
reg    lsm_instance_reg_file_ce1_local;
reg   [4:0] lsm_instance_reg_file_address1_local;
reg    lsm_instance_reg_file_ce0_local;
reg   [4:0] lsm_instance_reg_file_address0_local;
reg    lsm_instance_reg_file_we0_local;
reg    lsm_instance_reg_file_we1_local;
reg   [31:0] lsm_instance_reg_file_d1_local;
reg    lsm_instance_mem_ce0_local;
reg   [9:0] lsm_instance_mem_address0_local;
reg    lsm_instance_mem_we0_local;
wire   [0:0] result_4_fu_224_p2;
wire   [9:0] address_1_fu_258_p1;
wire   [9:0] address_fu_267_p1;
wire   [9:0] mem_addr_fu_294_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_condition_174;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

execute_lsm_instance_reg_file_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
lsm_instance_reg_file_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lsm_instance_reg_file_address0_local),
    .ce0(lsm_instance_reg_file_ce0_local),
    .we0(lsm_instance_reg_file_we0_local),
    .d0(imd_data),
    .q0(lsm_instance_reg_file_q0),
    .address1(lsm_instance_reg_file_address1_local),
    .ce1(lsm_instance_reg_file_ce1_local),
    .we1(lsm_instance_reg_file_we1_local),
    .d1(lsm_instance_reg_file_d1_local),
    .q1(lsm_instance_reg_file_q1)
);

execute_lsm_instance_mem_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
lsm_instance_mem_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lsm_instance_mem_address0_local),
    .ce0(lsm_instance_mem_ce0_local),
    .we0(lsm_instance_mem_we0_local),
    .d0(lsm_instance_reg_file_q1),
    .q0(lsm_instance_mem_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((opcode_read_read_fu_80_p2 == 4'd1)) begin
            result_6_reg_159 <= result_fu_252_p2;
        end else if ((opcode_read_read_fu_80_p2 == 4'd2)) begin
            result_6_reg_159 <= result_1_fu_246_p2;
        end else if ((opcode_read_read_fu_80_p2 == 4'd3)) begin
            result_6_reg_159 <= result_2_fu_240_p2;
        end else if ((opcode_read_read_fu_80_p2 == 4'd4)) begin
            result_6_reg_159 <= result_3_fu_234_p2;
        end else if ((opcode_read_read_fu_80_p2 == 4'd8)) begin
            result_6_reg_159 <= zext_ln51_fu_230_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln12_1_reg_366 <= grp_fu_189_p2;
        opcode_read_reg_331 <= opcode;
        rc_addr_read_reg_324 <= rc_addr;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        lsm_instance_reg_file_addr_1_reg_318 <= zext_ln19_1_fu_199_p1;
        lsm_instance_reg_file_addr_reg_312 <= zext_ln19_fu_194_p1;
        ra_addr_read_reg_307 <= ra_addr;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((~(opcode_read_reg_331 == 4'd5) & ~(opcode_read_reg_331 == 4'd9) & ~(opcode_read_reg_331 == 4'd6) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & ((opcode_read_reg_331 == 4'd5) | (opcode_read_reg_331 == 4'd9))))) begin
        ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6 = lsm_instance_reg_file_q0;
    end else if (((opcode_read_reg_331 == 4'd6) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6 = lsm_instance_mem_q0;
    end else begin
        ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lsm_instance_mem_address0_local = zext_ln89_1_fu_298_p1;
    end else if (((opcode_read_read_fu_80_p2 == 4'd6) & (1'b1 == ap_CS_fsm_state2))) begin
        lsm_instance_mem_address0_local = zext_ln94_fu_271_p1;
    end else if (((opcode_read_read_fu_80_p2 == 4'd5) & (1'b1 == ap_CS_fsm_state2))) begin
        lsm_instance_mem_address0_local = zext_ln89_fu_262_p1;
    end else begin
        lsm_instance_mem_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((opcode_read_read_fu_80_p2 == 4'd6) & (1'b1 == ap_CS_fsm_state2)) | ((opcode_read_read_fu_80_p2 == 4'd5) & (1'b1 == ap_CS_fsm_state2)))) begin
        lsm_instance_mem_ce0_local = 1'b1;
    end else begin
        lsm_instance_mem_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((opcode_read_read_fu_80_p2 == 4'd6) & (1'b1 == ap_CS_fsm_state2))) begin
        lsm_instance_mem_we0_local = 1'b1;
    end else begin
        lsm_instance_mem_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        lsm_instance_reg_file_address0_local = zext_ln19_2_fu_303_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        lsm_instance_reg_file_address0_local = lsm_instance_reg_file_addr_reg_312;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        lsm_instance_reg_file_address0_local = zext_ln19_1_fu_199_p1;
    end else begin
        lsm_instance_reg_file_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((opcode_read_reg_331 == 4'd6) & (1'b1 == ap_CS_fsm_state3))) begin
        lsm_instance_reg_file_address1_local = lsm_instance_reg_file_addr_1_reg_318;
    end else if (((icmp_ln12_1_reg_366 == 1'd0) & (opcode_read_reg_331 == 4'd5) & (1'b1 == ap_CS_fsm_state3))) begin
        lsm_instance_reg_file_address1_local = lsm_instance_reg_file_addr_reg_312;
    end else if (((1'b1 == ap_CS_fsm_state3) & ((((((opcode_read_reg_331 == 4'd4) & (icmp_ln12_2_fu_276_p2 == 1'd0)) | ((opcode_read_reg_331 == 4'd8) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd3) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd2) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd1) & (icmp_ln12_2_fu_276_p2 == 1'd0))))) begin
        lsm_instance_reg_file_address1_local = zext_ln13_fu_281_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        lsm_instance_reg_file_address1_local = zext_ln19_fu_194_p1;
    end else begin
        lsm_instance_reg_file_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        lsm_instance_reg_file_ce0_local = 1'b1;
    end else begin
        lsm_instance_reg_file_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((icmp_ln12_1_reg_366 == 1'd0) & (opcode_read_reg_331 == 4'd5) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state3) & ((((((opcode_read_reg_331 == 4'd4) & (icmp_ln12_2_fu_276_p2 == 1'd0)) | ((opcode_read_reg_331 == 4'd8) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd3) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd2) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd1) & (icmp_ln12_2_fu_276_p2 == 1'd0)))) | ((opcode_read_reg_331 == 4'd6) & (1'b1 == ap_CS_fsm_state3)))) begin
        lsm_instance_reg_file_ce1_local = 1'b1;
    end else begin
        lsm_instance_reg_file_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if (((icmp_ln12_1_reg_366 == 1'd0) & (opcode_read_reg_331 == 4'd5))) begin
            lsm_instance_reg_file_d1_local = lsm_instance_mem_q0;
        end else if ((1'b1 == ap_condition_174)) begin
            lsm_instance_reg_file_d1_local = result_6_reg_159;
        end else begin
            lsm_instance_reg_file_d1_local = 'bx;
        end
    end else begin
        lsm_instance_reg_file_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((grp_fu_189_p2 == 1'd0) & (opcode_read_read_fu_80_p2 == 4'd9) & (1'b1 == ap_CS_fsm_state2))) begin
        lsm_instance_reg_file_we0_local = 1'b1;
    end else begin
        lsm_instance_reg_file_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln12_1_reg_366 == 1'd0) & (opcode_read_reg_331 == 4'd5) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state3) & ((((((opcode_read_reg_331 == 4'd4) & (icmp_ln12_2_fu_276_p2 == 1'd0)) | ((opcode_read_reg_331 == 4'd8) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd3) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd2) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd1) & (icmp_ln12_2_fu_276_p2 == 1'd0)))))) begin
        lsm_instance_reg_file_we1_local = 1'b1;
    end else begin
        lsm_instance_reg_file_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(opcode_read_read_fu_80_p2 == 4'd9) & ~(opcode_read_read_fu_80_p2 == 4'd6) & ~(opcode_read_read_fu_80_p2 == 4'd5) & ~(opcode_read_read_fu_80_p2 == 4'd1) & ~(opcode_read_read_fu_80_p2 == 4'd2) & ~(opcode_read_read_fu_80_p2 == 4'd3) & ~(opcode_read_read_fu_80_p2 == 4'd4) & ~(opcode_read_read_fu_80_p2 == 4'd8) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & ((opcode_read_reg_331 == 4'd1) | ((opcode_read_reg_331 == 4'd2) | ((opcode_read_reg_331 == 4'd3) | ((opcode_read_reg_331 == 4'd4) | (opcode_read_reg_331 == 4'd8))))))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign address_1_fu_258_p1 = lsm_instance_reg_file_q0[9:0];

assign address_fu_267_p1 = lsm_instance_reg_file_q0[9:0];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_condition_174 = ((((((opcode_read_reg_331 == 4'd4) & (icmp_ln12_2_fu_276_p2 == 1'd0)) | ((opcode_read_reg_331 == 4'd8) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd3) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd2) & (icmp_ln12_2_fu_276_p2 == 1'd0))) | ((opcode_read_reg_331 == 4'd1) & (icmp_ln12_2_fu_276_p2 == 1'd0)));
end

assign ap_return = ap_phi_mux_retval_0_0_0_0_phi_fu_178_p6;

assign grp_fu_189_p2 = ((ra_addr_read_reg_307 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln12_2_fu_276_p2 = ((rc_addr_read_reg_324 == 5'd0) ? 1'b1 : 1'b0);

assign mem_addr_fu_294_p1 = lsm_instance_reg_file_q1[9:0];

assign opcode_read_read_fu_80_p2 = opcode;

assign result_1_fu_246_p2 = (lsm_instance_reg_file_q1 - lsm_instance_reg_file_q0);

assign result_2_fu_240_p2 = (lsm_instance_reg_file_q1 & lsm_instance_reg_file_q0);

assign result_3_fu_234_p2 = (lsm_instance_reg_file_q1 | lsm_instance_reg_file_q0);

assign result_4_fu_224_p2 = ((lsm_instance_reg_file_q1 == lsm_instance_reg_file_q0) ? 1'b1 : 1'b0);

assign result_fu_252_p2 = (lsm_instance_reg_file_q0 + lsm_instance_reg_file_q1);

assign zext_ln13_fu_281_p1 = rc_addr_read_reg_324;

assign zext_ln19_1_fu_199_p1 = rb_addr;

assign zext_ln19_2_fu_303_p1 = rc_addr_read_reg_324;

assign zext_ln19_fu_194_p1 = ra_addr;

assign zext_ln51_fu_230_p1 = result_4_fu_224_p2;

assign zext_ln89_1_fu_298_p1 = mem_addr_fu_294_p1;

assign zext_ln89_fu_262_p1 = address_1_fu_258_p1;

assign zext_ln94_fu_271_p1 = address_fu_267_p1;

endmodule //execute
